// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

type AdminClient = SupabaseClient<Database>;

function detectKeyKind(key: string): "publishable" | "secret" | "legacy_jwt" | "unknown" {
  if (key.startsWith("sb_publishable_")) return "publishable";
  if (key.startsWith("sb_secret_")) return "secret";
  if (key.startsWith("sb_")) return "unknown";
  if (key.startsWith("eyJ")) return "legacy_jwt";
  return "unknown";
}

function createSupabaseAdminClient(): AdminClient | null {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.warn(`[SupabaseAdmin] Missing environment variable(s): ${missing.join(', ')}. Server-side Supabase operations disabled.`);
    return null;
  }

  const kind = detectKeyKind(SUPABASE_SERVICE_ROLE_KEY);
  if (kind === "publishable") {
    console.error(`[SupabaseAdmin] SUPABASE_SERVICE_ROLE_KEY is a publishable key (starts with sb_publishable_). It CANNOT be used for admin operations. Use a secret key (sb_secret_...) or a legacy service_role JWT (eyJ...) instead.`);
    return null;
  }
  if (kind === "unknown") {
    console.warn(`[SupabaseAdmin] SUPABASE_SERVICE_ROLE_KEY has an unrecognised format. Admin operations may fail.`);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

const ADMIN_ERR = new Error('SupabaseAdmin not configured');

function makeAdminStub(depth = 0): any {
  if (depth > 5) return makeAdminStub(0);
  const fn: any = () => makeAdminStub(depth + 1);
  fn.data = null;
  fn.error = ADMIN_ERR;
  fn.then = (resolve: any) => resolve({ data: null, error: ADMIN_ERR });
  return new Proxy(fn, {
    get(target, prop) {
      if (prop === 'then') return target.then;
      if (prop === 'data' || prop === 'error') return target[prop];
      return makeAdminStub(depth + 1);
    },
    apply(_target, _thisArg, _args) {
      return makeAdminStub(depth + 1);
    },
  });
}

// Do NOT cache null — retry on every access so env-var changes take effect without restart
const adminStub = makeAdminStub();

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as AdminClient, {
  get(_, prop, receiver) {
    const client = createSupabaseAdminClient();
    if (!client) return Reflect.get(adminStub, prop, adminStub);
    return Reflect.get(client, prop, receiver);
  },
});
