// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

type AdminClient = SupabaseClient<Database>;

function createSupabaseAdminClient(): AdminClient | null {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.warn(`[SupabaseAdmin] Missing environment variable(s): ${missing.join(', ')}. Server-side Supabase operations disabled.`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: AdminClient | null | undefined;

// Graceful stub for when env vars are missing.
const adminStub = new Proxy({} as AdminClient, {
  get(_, prop) {
    console.warn(`[SupabaseAdmin] Cannot perform "${String(prop)}": admin client not initialized (missing env vars).`);
    return () => Promise.resolve({ data: null, error: new Error('SupabaseAdmin not configured') });
  },
});

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as AdminClient, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    if (!_supabaseAdmin) return Reflect.get(adminStub, prop, adminStub);
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
